export const MessageType = {
    ERROR: { code: -1, description: "协议错误/非法数据包" },
    SUCCESS: { code: 0, description: "成功响应" },

    LOGIN: { code: 100, description: "登录" },
    LOGOUT: { code: 101, description: "退出登录" },
    LOGIN_EXPIRED: { code: 102, description: "登录过期" },
    REFRESH_TOKEN: { code: 103, description: "刷新 Token" },
    FORCE_LOGOUT: { code: 104, description: "强制下线" },
    TOKEN_ERROR: { code: 105, description: "Token 错误" },
    NOT_LOGIN: { code: 106, description: "未登录" },
    LOGIN_FAILED_TOO_MANY_TIMES: { code: 107, description: "登录失败次数过多" },

    REGISTER: { code: 200, description: "用户注册" },
    CONNECT: { code: 201, description: "建立连接" },
    DISCONNECT: { code: 202, description: "断开连接" },
    DUPLICATE_LOGIN: { code: 203, description: "异地登录" },
    PRESENCE_UPDATE: { code: 204, description: "在线状态更新" },
    LAST_SEEN_UPDATE: { code: 205, description: "最后在线时间更新" },
    HEART_BEAT: { code: 206, description: "心跳" },
    HEART_BEAT_SUCCESS: { code: 207, description: "心跳成功" },
    HEART_BEAT_FAILED: { code: 208, description: "心跳失败" },
    REGISTER_SUCCESS: { code: 209, description: "注册成功" },
    REGISTER_FAILED: { code: 210, description: "注册失败" },

    REACTION_ADD: { code: 400, description: "添加表情反应" },
    REACTION_REMOVE: { code: 401, description: "移除表情反应" },

    USER: { code: 500, description: "普通用户" },
    ROBOT: { code: 501, description: "机器人" },
    PUBLIC_ACCOUNT: { code: 502, description: "公众号" },
    CUSTOMER_SERVICE: { code: 503, description: "客服" },

    ADD_FRIEND: { code: 550, description: "添加好友" },
    REMOVE_FRIEND: { code: 551, description: "删除好友" },
    BLOCK_USER: { code: 552, description: "拉黑用户" },
    UNBLOCK_USER: { code: 553, description: "解除拉黑" },
    FRIEND_REQUEST: { code: 554, description: "好友请求" },

    UPLOAD_FILE: { code: 600, description: "文件上传" },
    DOWNLOAD_FILE: { code: 601, description: "文件下载" },
    SHARE_FILE: { code: 602, description: "文件分享" },
    CHUNK_UPLOAD: { code: 603, description: "分片上传" },
    CHUNK_COMPLETE: { code: 604, description: "分片合并完成" },

    RTC_START_AUDIO_CALL: { code: 700, description: "发起语音通话" },
    RTC_START_VIDEO_CALL: { code: 701, description: "发起视频通话" },
    RTC_ACCEPT: { code: 702, description: "接受通话" },
    RTC_REJECT: { code: 703, description: "拒绝通话" },
    RTC_CANCEL: { code: 704, description: "取消通话" },
    RTC_FAILED: { code: 705, description: "通话失败" },
    RTC_HANGUP: { code: 706, description: "挂断通话" },
    RTC_CANDIDATE: { code: 707, description: "同步 candidate" },
    RTC_OFFLINE: { code: 708, description: "对方离线" },

    SYSTEM_NOTIFICATION: { code: 900, description: "系统通知" },
    MODERATION_ACTION: { code: 901, description: "平台管理操作" },
    AUDIT_LOG: { code: 902, description: "审计日志记录" },

    SINGLE_MESSAGE: { code: 1000, description: "单聊消息" },
    GROUP_MESSAGE: { code: 1001, description: "群聊消息" },
    VIDEO_MESSAGE: { code: 1002, description: "视频消息" },
    SYSTEM_MESSAGE: { code: 1003, description: "系统消息" },
    BROADCAST_MESSAGE: { code: 1004, description: "广播消息" },
    GROUP_OPERATION: { code: 1005, description: "群组操作（通用）" },
    MESSAGE_OPERATION: { code: 1006, description: "消息操作 (通用)" },

    UNKNOWN: { code: 9999, description: "未知指令" },
} as const;
